# Generated by Django 6.0.6 on 2026-06-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'casts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Runtime in minutes')),
                ('casts', models.ManyToManyField(blank=True, related_name='%(class)s_set', to='theatre.cast')),
                ('categories', models.ManyToManyField(blank=True, related_name='%(class)s_set', to='theatre.category')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('seasons', models.PositiveIntegerField(default=1)),
                ('episodes_per_season', models.PositiveIntegerField(default=1)),
                ('casts', models.ManyToManyField(blank=True, related_name='%(class)s_set', to='theatre.cast')),
                ('categories', models.ManyToManyField(blank=True, related_name='%(class)s_set', to='theatre.category')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'db_table': 'series',
            },
        ),
    ]
