# Generated by Django 6.0.6 on 2026-06-24 19:32

import bookstore.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[bookstore.models.validate_category_name])),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, validators=[bookstore.models.validate_title_length], verbose_name='Book Title')),
                ('description', models.TextField(verbose_name='Book Description')),
                ('rate', models.PositiveIntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='books', to='bookstore.category')),
            ],
            options={
                'verbose_name': 'Book Model',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_title', models.CharField(max_length=255, verbose_name='Author Title')),
                ('book_title', models.CharField(max_length=255, verbose_name='Book Title')),
                ('isbn_number', models.CharField(editable=False, max_length=17, unique=True, verbose_name='ISBN Number')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isbn', to='bookstore.book')),
            ],
            options={
                'verbose_name': 'ISBN',
                'verbose_name_plural': 'ISBNs',
                'db_table': 'isbns',
            },
        ),
    ]
